# Build Stage - Run tests and compile the project
FROM maven:3.8.1-openjdk-11 AS build
WORKDIR /usr/src/app
COPY ./src /usr/src/app/src
COPY ./pom.xml /usr/src/app/pom.xml
RUN mvn clean verify

# Run Stage - Copy the artifact from the build stage and run the microservice
FROM openjdk:11-jre-slim
WORKDIR /usr/app
COPY --from=build /usr/src/app/target/*.jar ./app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]